apiVersion: apps/v1

kind: Deployment 

metadata:
  name: test-api-deployment
  labels: 
    app: test-api
  namespace: production

spec:
  template:
    metadata: 
      name: test-api
      labels:
        app: test-api
    spec:
      containers:
        - name: test-api
          image: rodrigoborba/test-api
          env:
            - name: MONGODB_SERVER
              value: database-service

  replicas: 2 
  selector:
    matchLabels:
      app: test-api